truncate table CURRENT_INVENTORY;
truncate table CX_YSKQ;
truncate table RP_FILLRATE;
truncate table RP_IN_MONTH;
truncate table SALE_VSHOP_DAILY;
truncate table T_VENDER_BUDGET;
truncate table T_VENDER_SCORECARD_YB;
truncate table T_VENDERSGROUPID_BUDGET;
truncate table T_VENDERSGROUPID_SCORECARD_YB;
truncate table VENDER_GOODS_SHOP;
truncate table XSALE_VSHOP_DAILY;
truncate table AMS_PURCHASE;
truncate table AMS_PURCHASEITEM
;
truncate table CANCELEIREADLOG;
truncate table CANCELINSTALL;
truncate table CANCELINSTALLITEM;
truncate table CAT_AMS_PURCHASE;
truncate table CAT_CANCELINSTALL;
truncate table CAT_ELECINSTALL;
truncate table CAT_ORDER;
truncate table CAT_ORDER_BAK;
truncate table CAT_RECEIPT;
truncate table CAT_RET;
truncate table CAT_RETNOTICE;
truncate table CAT_SALEPICK;
truncate table CERTIFICATE;
truncate table CERTIFICATEITEM;
truncate table CERTIFICATEITEMIMG;
truncate table COUTCHARGECHK;
truncate table COUTCHARGECHKITEM;
truncate table ECVENDERDEDUCTION;
truncate table ELECINSTALL;
truncate table ELECINSTALLITEM;
truncate table ELECINSTALLREADLOG;
truncate table LIQUIDATION;
truncate table NETINCARDETAIL;
truncate table NETORDERDETAIL;
truncate table NETORDERLOG;
truncate table NETORDERSTATUS;
truncate table OICHARGE;
truncate table PAYMENTFEEITEM0;
truncate table PAYMENTSHEETITEM0;
truncate table PROMSHARE;
truncate table PROMSHAREITEM;
truncate table PURCHASE;
truncate table PURCHASE_BAK;
truncate table PURCHASE0;
truncate table PURCHASE0_BAK;
truncate table PURCHASEITEM;
truncate table PURCHASEITEM_BAK;
truncate table RECEIPT;
truncate table RECEIPTITEM;
truncate table RET;
truncate table RETITEM;
truncate table RETNOTICE;
truncate table RETNOTICEITEM;
truncate table SALEPICK;
truncate table SALEPICKITEM;
truncate table STKCOSTADJ;
truncate table STKCOSTADJITEM;
truncate table CAT_GOODSSHOP;
truncate table CAT_SALE_DAILY;
truncate table CERTASKLIST;
truncate table CERTASKLISTLOG;
truncate table DAILY_INVENTORY;
truncate table FAS_INVOICE;
truncate table FAS_PROMSHARE;
truncate table FAS_PROMSHAREITEM;
truncate table FAS_SALECOST;
truncate table FAS_SALECOSTITEM;
truncate table FAS_XSALE;
truncate table FAS_XSALEITEM;
truncate table GOODSSHOPA;
truncate table GPACKAGE_VSS;
truncate table ITF_NETINCARDETAIL;
truncate table ITF_NETINCARHEAD;
truncate table ITF_NETORDER;
truncate table MSCMTASKKEY;
truncate table MSCMTASKLIST;
truncate table TOBACCOSHOP;
truncate table TOBACCOTASK;
truncate table TOBACCOTASKBAK;
truncate table TOBACCOTASKITEM;
truncate table TOBACCOVENDER;
truncate table TOBACCOBARCODE;
truncate table V_GOODSSHOP;
truncate table CASHPAY;
truncate table CASHPAYITEM;
truncate table CASHPAYLATEFEE;
truncate table CASHPAYPREREC;
truncate table CHARGESUM;
truncate table CHARGESUM0;
truncate table LIQUIDATIONITEM;
truncate table LIQUIDATIONLOG;
truncate table PAYMENTFEEITEM;
truncate table PAYMENTNOTE;
truncate table PAYMENTNOTE0;
truncate table PAYMENTNOTECHARGE;
truncate table PAYMENTNOTEDTL;
truncate table PAYMENTNOTEDTL0;
truncate table PAYMENTNOTEITEM;
truncate table PAYMENTNOTEITEM0;
truncate table PAYMENTNOTEVENDERASK;
truncate table PAYMENTPREPAYITEM;
truncate table PAYMENTPREPAYITEM0;
truncate table PAYMENTSHEET;
truncate table PAYMENTSHEET0;
truncate table PAYMENTSHEETDLT;
truncate table PAYMENTSHEETDLT0;
truncate table PAYMENTSHEETGOODSINFO;
truncate table PAYMENTSHEETGOODSINFO0;
truncate table PAYMENTSHEETITEM;
truncate table UNPAIDSHEET;
truncate table UNPAIDSHEET0;
truncate table VENDERCASHREC;
truncate table VENDERINVOICE;
truncate table VENDERINVOICEITEM;
truncate table VENDERPAYADVICEM;
truncate table VENDERPAYSTATUS;
truncate table LOG_WORK;
truncate table USER_LIST;
truncate table USER_ENVIRONMENT;
truncate table USER_ROLE;
truncate table FILEBODY;
truncate table FILEINFO;
truncate table MAIL_BODY;
truncate table MAIL_GROUP;
truncate table MAIL_GROUP_DETAIL;
truncate table MAIL_RECEIPTOR;
truncate table MAIL_SENDER;
truncate table MAIL_TITLE;
truncate table NOTEBOARD_FBODY;
truncate table NOTEBOARD_FINFO;
truncate table NOTEBOARD_LOG;
truncate table NOTEBOARD_TEXT;
truncate table NOTEBOARD_TITLE;
truncate table VENDERMSG;
truncate table VENDERMSG_LOG;
truncate table VENDERMSGITEM;
truncate table AMS_VENDER;
truncate table BANKACCOUNT;
truncate table BOOK;
truncate table CATEGORY;
truncate table CERT_EXPORT_VENDER;
truncate table CERTIFICATECATEGORY;
truncate table CERTIFICATECONFIG;
truncate table CERTIFICATERELATION;
truncate table CERTIFICATETYPE;
truncate table CHARGECODE;
truncate table DELIVERTIME;
truncate table DEPARTMENT;
truncate table EDI_VENDER;
truncate table EDI_VENDERITEM;
truncate table GDS_GOODS;
truncate table GDS_TASK_LIST;
truncate table GOODS;
truncate table GOODSGSPEXT;
truncate table GPACKAGE;
truncate table INNERVENDER;
truncate table INSTALLSERVER;
truncate table LATEFEEINFO;
truncate table LOOKUP;
truncate table LOOKUPITEM;
truncate table MASTER_CATEGORY;
truncate table MASTER_GOODS;
truncate table MASTER_SHOP;
truncate table MASTER_VENDER;
truncate table MASTER_VENDERBANK;
truncate table NETGOODSFLOOR;
truncate table NETINCARHEAD;
truncate table NETLARGERVENDER;
truncate table NETORDERHEAD;
truncate table NETORDERPARA;
truncate table NETORDERPARADATE;
truncate table NETORDERTIME;
truncate table NETORDERTIMEST;
truncate table NETPSDATE;
truncate table PAYMODE;
truncate table PAYSHOP;
truncate table PAYTYPE;
truncate table PLACE;
truncate table REGION;
truncate table SHOP;
truncate table VENDER;
truncate table VENDER_BANK;
truncate table VENDER_DIY;
truncate table VENDER_HOLIDAY;
truncate table VENDER_HOLIDAYEXP;
truncate table VENDER_HOLIDAYITEM;
truncate table VENDERCARD;
truncate table VENDERCATEGORYRELATION;
truncate table VENDEREXT;


--????????
DROP SEQUENCE DBUSRVSS.CERTASKID;
 CREATE SEQUENCE DBUSRVSS.CERTASKID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;

DROP SEQUENCE DBUSRVSS.FILEINFO_ID;
 CREATE SEQUENCE DBUSRVSS.FILEINFO_ID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.LOG_WORK_ID;
 CREATE SEQUENCE DBUSRVSS.LOG_WORK_ID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.MAIL_ID;
 CREATE SEQUENCE DBUSRVSS.MAIL_ID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.NOTEBOARD_LOG_ID;
 CREATE SEQUENCE DBUSRVSS.NOTEBOARD_LOG_ID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.SEQ_CERTASKID;
 CREATE SEQUENCE DBUSRVSS.SEQ_CERTASKID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.SEQ_VENDERLQCONFIGLOG;
 CREATE SEQUENCE DBUSRVSS.SEQ_VENDERLQCONFIGLOG START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.SYSLOG_ID;
 CREATE SEQUENCE DBUSRVSS.SYSLOG_ID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.VENDERINVOICEITEM_ID;
 CREATE SEQUENCE DBUSRVSS.VENDERINVOICEITEM_ID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.VENDERMSGITEM_ID;
 CREATE SEQUENCE DBUSRVSS.VENDERMSGITEM_ID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
DROP SEQUENCE DBUSRVSS.VENDERMSG_LOG_ID;
 CREATE SEQUENCE DBUSRVSS.VENDERMSG_LOG_ID START WITH  1 MAXVALUE 9999999999999  MINVALUE 1 NOCYCLE  CACHE 20 NOORDER;
 
 
 --????????
 --??????????????
 insert into user_list (USERID, USERNAME, USERCLASS, USERSTATUS, LOGINID, PASSWORD, SHOPID, MENUROOT)
values (0, '?????, 0, 0, 'admin', '25d55ad283aa400af464c76d713c07ad', 'AAAA', 20);
insert into user_role values (0,-10);
insert into user_environment(0,'venderid','admin');

--??????????????
--shop
--goods
--category
--vender


--???????????????
--????opy2userlist?????

--???JOB??????6?????daily.daily_work;

